// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nsted.Data;

#nullable disable

namespace Nsted.Migrations
{
    [DbContext(typeof(NstedDbContext))]
    [Migration("20231122133616_Sjekkliste")]
    partial class Sjekkliste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nsted.Models.Kunde", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Epost")
                        .HasColumnType("longtext");

                    b.Property<string>("Etternavn")
                        .HasColumnType("longtext");

                    b.Property<string>("Fornavn")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Nsted.Models.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Notat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Produkttype")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serienummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceRep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Årsmodell")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Servicer");
                });

            modelBuilder.Entity("Nsted.Models.Sjekkliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Serienummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkBremser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkBremsesylinder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkClutchLamellerForSlitasje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkHydrauliskSylinder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkKile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkKjedestrammer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkKnappekasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkLagerForTrommel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkLedningsnett")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkPinonLager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkRadio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkRyngsylinder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkSlanger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SjekkWire")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkifteOljeGirBoks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkifteOljeTank")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TestHydraulikkblokk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sjekklister");
                });
#pragma warning restore 612, 618
        }
    }
}
