// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nsted.Models;

#nullable disable

namespace Nsted.Migrations
{
    [DbContext(typeof(NstedDbContext))]
    [Migration("20231106112444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nsted.Models.Ansatt", b =>
                {
                    b.Property<int>("AnsattNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnsattNr");

                    b.ToTable("Ansatte");
                });

            modelBuilder.Entity("Nsted.Models.Kunde", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Epost")
                        .HasColumnType("longtext");

                    b.Property<string>("Etternavn")
                        .HasColumnType("longtext");

                    b.Property<string>("Fornavn")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Nsted.Models.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Notat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Produkttype")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serienummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceRep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Årsmodell")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Servicer");
                });
#pragma warning restore 612, 618
        }
    }
}
